include:
  - project: ${PIPELINE_REPOSITORY_PREFIX}devenv/gitlab/pipelines
    ref: 4.0.3
    file:
      - merge-request.gitlab-ci.yml
      - scheduled-checks.gitlab-ci.yml

build and verify:
  variables:
    JDK_VERSION: 'jdk21'
  script:
    - echo "No services in project, docker/helm build skipped"
    - touch chart.env

deploy mr stand:
  rules:
    - when: never

cleanup:
  rules:
    - when: never

scheduled build:
  # В проекте нет docker-образов поэтому из after_script
  # шаблона убрано вычисление FULL_IMAGE_NAMES по docker-compose конфигу
  after_script:
    - mvn $MAVEN_RUN_OPTIONS org.cyclonedx:cyclonedx-maven-plugin:2.9.1:makeAggregateBom -DprojectType=application -DskipNotDeployed=false -DoutputFormat=json -Dverbose=true $MAVEN_PIPELINE_OPTIONS $MAVEN_EXTRA_BUILD_OPTIONS
  artifacts:
    paths:
      - target/bom.json
    expire_in: 2 days

zap dast:
  variables:
    DAST_URI: ''

defectdojo:
  variables:
    DEFECTDOJO_SONARQUBE_PROJECT_KEY: 'net.n2oapp.platform:n2o-boot-platform'
