= Инструкции по миграции

== 5.2.0
* Из платформы исключён устаревший JWT-стартер и связанные с ним функции прозрачной отправки JWT через feign и cxf. Дополнительное пояснение: https://jira.i-novus.ru/browse/NNOP-222
* ВАЖНО! Пропатченный старый ru.i-novus.components:liquibase-core версии 3.6.2.x.inovus был исключён из платформы. В прикладных проектах требуется замена на стандартный org.liquibase:liquibase-core, который определяется в зависимостях spring boot. Причина - несовместимость с новым spring boot: https://jira.i-novus.ru/browse/EGISZNRPLATFORM-1301
* Теперь платформа поддерживает "сборку" конфигураций kubernetes (раньше поддерживались только конфигурации docker compose), и включение делается не через профиль `docker-config-filter` как раньше, а добавлением плагина в рутовый pom-файл проекта. Также изменена папка с конфигурациями docker compose по умолчанию, теперь это `.docker-compose`. Папку по умолчанию можно переопределить через свойства. Подробности в link:/n2o-platform-parent/README.adoc[документации n2o-boot-platform-parent].

== 5.1.1
* Контекст актуатора теперь дефолтный `/actuator`, раньше был `/monitoring`.

== 5.1

==== Изменения в платформе
* Файлы конфигурации bootstrap.yml стали deprecated в новых версиях spring boot и spring cloud, поэтому платформа их также не поддерживает. Вся конфигурация теперь делается через application.yml. В частности для считывания конфигурации из облака используется новое свойство spring.config.import. Подробнее: +
https://docs.spring.io/spring-cloud-consul/docs/current/reference/html/#spring-cloud-consul-config
https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4
https://docs.spring.io/spring-boot/docs/2.7.5/reference/htmlsingle/#features.external-config
* Consul Configuration теперь по умолчанию обязателен для старта приложения. Для тестов, использующих test-starter платформы, наоборот,
по умолчанию считывание конфигурации из Consul выключено.
* Формат по умолчанию для хранения настроек в Consul теперь YAML: https://docs.spring.io/spring-cloud-consul/docs/current/reference/html/#spring-cloud-consul-config-format
* Изменение имени модуля: n2o-platform-audit теперь называется n2o-platform-db-audit. Стартер и другие зависимости также поменяли свои имена соответственно.
* Удалён профиль `consul`. Для работы без Consul можно использовать способ описанный в link:/n2o-platform-ms/README.adoc[документации к n2o-platform-ms-starter].
* Свойство maven `config.server.enable` можно удалить, так как оно больше не влияет на использование внешнего сервера конфигураций, он теперь включен всегда.

==== Изменения в зависимостях
* Сделать миграции до Spring Boot 2.7.5: +
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes +
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes +
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes +
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes +
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide
* Сделать миграции до Spring Security 5.7: +
https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide +
https://github.com/spring-projects/spring-security/releases (секции Breaking Changes, начиная от версии 5.3)
* Сделать миграции до Spring Cloud 2021.0.5: +
https://spring.io/blog/2020/12/22/spring-cloud-2020-0-0-aka-ilford-is-available +
https://spring.io/blog/2021/12/02/spring-cloud-2021-0-0-codename-jubilee-has-been-released
* Сделать миграции до N2O Framework 7.23: +
https://n2o.i-novus.ru/docs/guides/migration/to_7_23/
