= Инструкции по миграции

== 6.4.0
* Переход на Java 21.
* Ключевые обновления зависимостей:
** Spring Boot 3.2=>3.5
*** https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.5-Release-Notes
*** https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes
*** https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes
** Spring Cloud Dependencies 2023.0.3=>2025.0.0
** loki-logback-appender 1.4.0=>2.0.0. Изменена xml схема конфигурации. Изменены дефолтные значения настроек. Добавлена настройка n2o.ms.loki.batch.size с дефолтным значением 1000. Данная настройка определяет количество сообщений в пакетах, отправляемых в Loki.
*** https://loki4j.github.io/loki-logback-appender/docs/migration
* *Важно!* Изменено поведение Spring data jpa: методы репозиториев, наследующиеся от JpaRepository<T, ID>, с @Query аннотациями на базе JPQL запросов должны начинать извлечение данных в конструкциях from от сущности T из сигнатуры JpaRepository.
Например, если объявлен репозиторий JpaRepository<Employee, Integer> с запросом
`@Query("SELECT c FROM Contact c WHERE c.owner.id IN (?1)")`, где Contact - сущность, то исполнение метода завершится с ошибкой. Однако, если переписать в таком виде `@Query("select c from Employee e inner join e.contacts c where e.id in (?1)")`, метод будет выполняться успешно. Судя по всему Spring data определяет Contact в выше приведённом примере как DTO.
* *Важно!* Переопределение версии org.apache.commons commons-lang3 на более старые приводит к отказу при запуске приложения. Spring Boot 3.5 не может динамически загрузить классы из старых версий commons-lang3 < 3.13.
* Начиная с Java 21, были ужесточены правила динамического подключения java агентов. В частности, использование Mockito без дополнительной конфигурации приводит к предупреждениям во время выполнения тестов https://javadoc.io/doc/org.mockito/mockito-core/latest/org.mockito/org/mockito/Mockito.html#0.3. Проекты, использующие в качестве родителя n2o-boot-platform-parent, должны быть лишены проблем с Mockito.

== 6.1.0
* Возвращен модуль `n2o-platform-web`

== 6.0.0
* Переход на Spring Boot 3.2. Для этого есть отдельный миграционный гайд: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide. В частности это значит, что минимальная поддерживаемая платформой версия Java теперь 17.
** Переход со Spring Cloud Sleuth на Micrometer Tracing: https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide
** Отправка трейсов теперь по умолчанию включена. Отключить можно настройкой `management.tracing.enabled=false`.
* В ms-стартер добавлен выключенный по умолчанию клиент конфигурации vault. Может повлиять, если в проекте он был уже подключен.
* Переход с Java EE на Jakarta EE. Это, например, значит, что нужно вместо пакетов `javax` использовать `jakarta`. А также, что нельзя использовать зависимости со старыми пакетами, будут ошибки `ClassNotFound` и `MethodNotFound`.
* Переход со swagger-спецификаций на openApi:
** Все настройки `jaxrs.swagger.\*` заменены на аналогичные настройки `jaxrs.openapi.*`.
** Настройка `jaxrs.swagger.resource-package` была заменена на `jaxrs.openapi.resource-packages`.
* Переход на openfeign 13.2. Возможны изменения при работе с прокси-клиентами на основе feign.
* Из платформы исключён модуль `n2o-platform-web`, который использовался для подключения n2o ui framework. Модуль вернётся в новых версиях платформы, когда n2o ui framework перейдёт на совместимый стек.

== 5.3.0
* Стартер проброса информации пользователя между сервисами(n2o-platform-userinfo-starter) перенесён в проект security-admin(security-userinfo-starter).

== 5.2.0
* Из платформы исключён устаревший JWT-стартер и связанные с ним функции прозрачной отправки JWT через feign и cxf. Дополнительное пояснение: https://jira.i-novus.ru/browse/NNOP-222
* ВАЖНО! Пропатченный старый ru.i-novus.components:liquibase-core версии 3.6.2.x.inovus был исключён из платформы. В прикладных проектах требуется замена на стандартный org.liquibase:liquibase-core, который определяется в зависимостях spring boot. Причина - несовместимость с новым spring boot: https://jira.i-novus.ru/browse/EGISZNRPLATFORM-1301
* Теперь платформа поддерживает "сборку" конфигураций kubernetes (раньше поддерживались только конфигурации docker compose), и включение делается не через профиль `docker-config-filter` как раньше, а добавлением плагина в рутовый pom-файл проекта. Также изменена папка с конфигурациями docker compose по умолчанию, теперь это `.docker-compose`. Папку по умолчанию можно переопределить через свойства. Подробности в link:/n2o-platform-parent/README.adoc[документации n2o-boot-platform-parent].

== 5.1.1
* Контекст актуатора теперь дефолтный `/actuator`, раньше был `/monitoring`.

== 5.1

==== Изменения в платформе
* Файлы конфигурации bootstrap.yml стали deprecated в новых версиях spring boot и spring cloud, поэтому платформа их также не поддерживает. Вся конфигурация теперь делается через application.yml. В частности для считывания конфигурации из облака используется новое свойство spring.config.import. Подробнее: +
https://docs.spring.io/spring-cloud-consul/docs/current/reference/html/#spring-cloud-consul-config
https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4
https://docs.spring.io/spring-boot/docs/2.7.5/reference/htmlsingle/#features.external-config
* Consul Configuration теперь по умолчанию обязателен для старта приложения. Для тестов, использующих test-starter платформы, наоборот,
по умолчанию считывание конфигурации из Consul выключено.
* Формат по умолчанию для хранения настроек в Consul теперь YAML: https://docs.spring.io/spring-cloud-consul/docs/current/reference/html/#spring-cloud-consul-config-format
* Изменение имени модуля: n2o-platform-audit теперь называется n2o-platform-db-audit. Стартер и другие зависимости также поменяли свои имена соответственно.
* Удалён профиль `consul`. Для работы без Consul можно использовать способ описанный в link:/n2o-platform-ms/README.adoc[документации к n2o-platform-ms-starter].
* Свойство maven `config.server.enable` можно удалить, так как оно больше не влияет на использование внешнего сервера конфигураций, он теперь включен всегда.

==== Изменения в зависимостях
* Сделать миграции до Spring Boot 2.7.5: +
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes +
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes +
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes +
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes +
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide
* Сделать миграции до Spring Security 5.7: +
https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide +
https://github.com/spring-projects/spring-security/releases (секции Breaking Changes, начиная от версии 5.3)
* Сделать миграции до Spring Cloud 2021.0.5: +
https://spring.io/blog/2020/12/22/spring-cloud-2020-0-0-aka-ilford-is-available +
https://spring.io/blog/2021/12/02/spring-cloud-2021-0-0-codename-jubilee-has-been-released
* Сделать миграции до N2O Framework 7.23: +
https://n2o.i-novus.ru/docs/guides/migration/to_7_23/
