= Документация
:toc:
:toclevels: 3
:toc-title: Содержание

= Возможности

Библиотека позволяет загружать небольшие справочные данные, обычно прошитые в коде клиента, в удаленный сервис при старте.
Например, клиентское приложение имеет свои права доступа, которые необходимо загрузить в микросервис безопасности.
Для этого достаточно создать файл permissions.json, добавить туда свои права доступа и задать адрес api сервиса безопасности.
Клиенское приложение выполнит REST запрос на эндпоинт /load в сервисе безопасности, отправив туда свои права доступа.
Сервис безопасности создаст недостающие, обновит существующие и удалит устаревшие права доступа для этого клиента.

= Сервер

== Подключение

Добавьте зависимость `n2o-platform-starter-loader-server`:
[source,xml]
----
<dependency>
  <groupId>net.n2oapp.platform</groupId>
  <artifactId>n2o-platform-starter-loader-server</artifactId>
</dependency>
----
Она добавит библиотеку серверных загрузчиков `n2o-platform-loader-server` и автоконфигуратор `n2o-platform-loader-autoconfigure`.

Создайте загрузчик данных используя интерфейс `ServerLoader`:

[source,java]
----
@Component
class MyServerLoader implements ServerLoader<List<MyModel>> {
    @Override
    public void load(List<MyModel> data, String subject) {
        //create new and update old
        //find unused by subject
        //delete unused
    }
}
----

Или используйте `RepositoryServerLoader`:

[source,java]
----
@Bean
RepositoryServerLoader<MyModel, MyEntity> myServerLoader(MyRepository repository) {
    return new RepositoryServerLoader<>(mapper, repository, finder);
}
----

Соедините REST сервис `/load` с вашим загрузчиком:

[source,java]
----
@Configuration
class MyLoadersConfiguration implements ServerLoaderConfigurer {
    @Override
    public void configure(ServerLoaderRunner runner) {
        runner.add(asObject(new MyServerLoader(), "myload", MyModel.class));
        //add something else ...
    }
}
----

== Использование

Отлаживайте ваш загрузчик через REST клиент `/load/{subject}/{target}`:

----
POST /load/me/myload
[
  {
    "code": "code1",
    "name": "name1"
  },
  ...
]
----

= Клиент

== Подключение

Добавьте зависимость:
[source,xml]
----
<dependency>
  <groupId>net.n2oapp.platform</groupId>
  <artifactId>n2o-platform-starter-loader-client</artifactId>
</dependency>
----
