= Документация
:toc:
:toclevels: 3
:toc-title: Содержание

= Описание
Родительская maven-конфигурация для всех проектов на основе платформы.

= Подключение
Пример подключения в корневой pom.xml проекта:
[source,xml]
----
<parent>
    <groupId>net.n2oapp.platform</groupId>
    <artifactId>n2o-boot-platform-parent</artifactId>
    <version>4.0.0-SNAPSHOT</version>
</parent>
----

= Использование JaCoCo
Включите профиль `jacoco`.

Добавьте в модули, содержащих тесты либо тестируемые классы, свойство:
[source,xml]
----
<properties>
    <jacoco.skip>false</jacoco.skip>
</properties>
----

В одномодульных проектах переопределите свойство `jacoco.aggregate.report.path`, поставьте значение по умолчанию:
----
<properties>
    <jacoco.aggregate.report.path>${project.basedir}/target/site/jacoco-aggregate</jacoco.aggregate.report.path>
</properties>
----

= Включение конфигурации через Consul
Включите профиль `consul`.

Необходимые условия работы:
1. Настройка `config.server.enable` должна переопределять значение `spring.cloud.consul.config.enabled` и `management.health.consul.enabled`.
Например, можно добавить в bootstrap.yml:
---
   spring:
     cloud:
       consul:
         config:
           enabled: ${config.server.enable}

   management:
     health:
       consul:
         enabled: ${config.server.enable}
---
2. Должен быть подключен стартер n2o-platform-starter-ms.

При запуске приложение будет запрашивать настройки из Consul по адресу consul-agent.local.

= Фильтрация конфигураций Docker
Включите профиль `docker-config-filter`.

При сборке во всех yml-файлах в папке docker-compose будут подставлены значения плейсхолдеров из свойств maven.
Полученные yml-файлы будут помещены в корне сборочной директории.
