:toc:
:toclevels: 3
:toc-title: Содержание

== Описание
Родительская maven-конфигурация для всех проектов на основе платформы.
Задаёт настройки по умолчанию: версии базовых плагинов maven, версию java, исключения из проверки для SonarQube, другие базовые настройки.
Наследует bom-файл платформы, который в свою очередь наследует парент pom от spring boot.

Также содержит профили для решения часто-возникающих проблем.

== Подключение
Пример подключения в корневой pom.xml проекта:
[source,xml]
----
<parent>
    <groupId>net.n2oapp.platform</groupId>
    <artifactId>n2o-boot-platform-parent</artifactId>
    <version>5.1.0-SNAPSHOT</version>
</parent>
----

== Использование JaCoCo
Включите профиль `jacoco`.

Добавьте в модули, содержащих тесты либо тестируемые классы, свойство:
[source,xml]
----
<properties>
    <jacoco.skip>false</jacoco.skip>
</properties>
----

В одномодульных проектах переопределите свойство `jacoco.aggregate.report.path`, поставьте значение по умолчанию:
[source,xml]
----
<properties>
    <jacoco.aggregate.report.path>${project.basedir}/target/site/jacoco-aggregate</jacoco.aggregate.report.path>
</properties>
----

Встроенная в платформу n2o boot конфигурация JaCoCo решает проблемы подсчёта покрытия в мультимодульных maven-проектах, описанным здесь способом: +
https://stackoverflow.com/questions/13031219/how-to-configure-multi-module-maven-sonar-jacoco-to-give-merged-coverage-rep/60639251#60639251

== Фильтрация конфигураций Docker Compose и Kubernetes
Эта функция позволяет "собирать" конфигурационные файлы docker и kubernetes, подставляя значения из maven.

При сборке в папках `${docker-compose.config.folder}` (по умолчанию .docker-compose) и `${k8s.config.folder}` (по умолчанию .k8s) во всех yaml-файлах будут подставлены значения плейсхолдеров из свойств maven.

==== Пример
Вместо `${rdm.version}` в yaml-конфигурации:
```
rdm-service:
    image: rdm/backend:${rdm.version}
```
будет подставлено значение свойства из pom-файла:
```
<properties>
    <rdm.version>1.4.3</rdm.version>
</properties>
```
Полученные yaml-файлы будут помещены в корне сборочной директории.

==== Подключение
Для включения этой функции нужно в рутовый pom-файл проекта добавить конфигурацию плагина:
```
<build>
    <plugins>
        <plugin>
            <artifactId>maven-resources-plugin</artifactId>
            <inherited>false</inherited>
            <executions>
                <execution>
                    <id>process-docker-config</id>
                    <phase>initialize</phase>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```
Тогда сборка конфигураций будет производиться только один раз за сборку (только для рутового pom-файла проекта) в фазе initialize.