= Документация


== Возможности
Стартер дает возможность вести аудит данных для каждой таблицы в бд фиксирует кто, когда и из какой системы создал и произвел изменения и дельту изменений.

== Общая схема реализация
Аудит основан на триггерах. К каждой таблице в бд приложения на этапе деплоя добавляются два триггера(audit_trigger и audit_trigger_full)
и таблица аудита, которая имеет формат названия audit.<схема аудируемой таблицы>$<аудируемая таблица>.
Также в основную таблицу добавятся колонки аудита (aud_who, aud_when, aud_source, aud_who_create, aud_when_create, aud_source_create).
Например есть таблица public.foo, то таблица аудита будет называться audit.public$foo и в таблицу public.foo добавятся 6 колонок.

== Описание таблицы аудита
[frame=ends]
|===
|*Колонка* |*Тип* |*Описание*

|aud_rec
|bigint
|Первичный ключ

|<колонка первичный ключ аудируемой таблицы>
|<тип колонки из аудируемой таблицы>
|Хранит значение колонки первичного ключа из аудируемой таблицы. Если в аудируемой таблицы первичный ключ составной, то будет столько же колонок

|type
|text
|Тип действия над строкой таблицы I - вставка, U - редактирование, D - удаление

|delta
|jsonb
|Разница строки до и после действия над строкой таблицы

|aud_when
|timestamp
|Когда было выполнено действие на строкой таблицы, по факту время начала транзакции

|aud_who
|varchar
|Пользователь, который выполнил действие над строкой таблицы. Если приложение не передает пользователя, то запишется пользователь бд

|aud_source
|varchar
|Система-источник, которая выполнила действие на строкой таблицы. Если приложение не передает это значение, то запишется значение DB

|data
|jsonb
|Хранит текущее состояние строки после действия над таблицей, или до действия в случае удаления. Если значение колонки null то она не отображается

|dump
|jsonb
|Начальные значения измененных атрибутов
|===

== Описание колонок аудита в исходной таблице
|===
|*Колонка* |*Тип* |*Описание*
|aud_when
|timestamp
|Время последнего изменения строки, по факту время начала транзакции

|aud_who
|varchar
|Пользователь, который последний раз менял строку таблицы. Если приложение не передает пользователя, то запишется пользователь бд

|aud_source
|varchar
|Система-источник, которая последний раз меняла строку таблицы. Если приложение не передает это значение, то запишется значение DB

|aud_when_create
|timestamp
|Время создания строки, по факту время начала транзакции

|aud_who_create
|varchar
|Пользователь, который создал строку таблицы. Если приложение не передает пользователя, то запишется пользователь бд

|aud_source_create
|varchar
|Система-источник, которая создала строку таблицы. Если приложение не передает это значение, то запишется значение DB

|===

== Подключение
----
<dependency>
  <groupId>net.n2oapp.platform</groupId>
  <artifactId>n2o-platform-starter-audit</artifactId>
</dependency>
----

== Передача пользователя и системы источника в аудит
Система при изменение данных в БД, вместе с запросом на изменение должна передавать контекст, содержащий информацию о системе и ее пользователя.
Контекст передается в той же транзакции, что производит изменение/запись,  следующим образом
----
SELECT set_config('app.user', 'userValue', true);
SELECT set_config('app.source', 'sourceValue', true);
----
:tip-caption: 💡

[TIP]
Система сама решает каким образом вызывать скрипты передачи контекста


== Исключение из аудита
По умолчанию все таблицы подлежат аудиту если ее не исключить.
Есть возможность исключить схему целиком, таблицу, либо часть колонок таблицы. Для этого надо добавить записи в таблицы
aud_excluded_schemas, aud_excluded_tables и aud_excluded_columns соответственно.

=== Зачем это нужно

Иногда у вас есть набор технических таблиц, которые не надо аудировать. У данного аудита есть предопределенный набор
схем и таблиц, которые по - умолчанию не аудируются (например, `databasechangelog` ликуйбейза). Но в вашем проекте могут быть какие - то еще,
предусмотреть все невозможно. Некоторые не технические таблицы тоже не надо аудировать (справочники и т.д.). В этом случае добавить в исключения и
аудит не будет их трогать.

=== Как это сделать

В ресурсах приложения необходимо создать папку `audit/customize`.
Туда по мере необходимости добавлять  liquibase-скрипты точно так же, как добавляем обычные скрипты с префиксами
`ГГГГММДДЧЧММ-описание-скрипта.xml`. Они будут включаться в changelog при каждом прогоне auditLiquibase-а.

Например вам нужно исключить схему Quartz-а из аудита. Для этого вам нужно создать файл `ГГГГММДДЧЧММ-exclude-quartz.xml` с таким содержимым:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.6.xsd">
    <changeSet id="ГГГГММДДЧЧММ-exclude-quartz" author="author" dbms="postgresql">
        <sql splitStatements="false">
            insert into aud_excluded_schemas(id, schema_name) values(nextval('aud_excluded_schemas_seq'), 'quartz');
        </sql>
    </changeSet>
</databaseChangeLog>
----



