initializr:
  groupId:
    value: net.n2oapp.microservice
  artifactId:
    value: n2o-microservice-app
  version:
    value: ${project.version}
  packageName:
    value: net.n2oapp.microservice.app
  name:
    value:
  description:
    value:
  javaVersions:
    - id: 17
      default: true
  languages:
    - name: Java
      id: java
      default: true
  packagings:
    - name: Jar
      id: jar
      default: true
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
  bootVersions:
    - name: 3.2.2
      id: 3.2.2
  dependencies:
    - name: N2O
      content:
        - name: JaxRs Server
          id: n2o-jaxrs-server
          groupId: net.n2oapp.platform
          artifactId: n2o-platform-starter-jaxrs-server
          description: Rest server provider powered by CXF
          bom: n2o-platform-bom
          aliases:
            - jaxrs server
        - name: JaxRs Client
          id: n2o-jaxrs-client
          groupId: net.n2oapp.platform
          artifactId: n2o-platform-starter-jaxrs-client
          description: Rest proxy client provider powered by CXF
          bom: n2o-platform-bom
          aliases:
            - jaxrs client
        - name: Feign Client
          id: n2o-feign-client
          groupId: net.n2oapp.platform
          artifactId: n2o-platform-starter-feign-client
          description: Rest proxy client provider powered by Feign
          bom: n2o-platform-bom
          aliases:
            - feign
            - client
        - name: MS
          id: n2o-ms
          groupId: net.n2oapp.platform
          artifactId: n2o-platform-starter-ms
          description: Observability and cloud configuration for microservices
          bom: n2o-platform-bom
          aliases:
            - ms
            - microservice
  env:
    repositories:
      i-novus-releases:
        name: I-Novus Repository
        url: http://maven.i-novus.ru/libs-release/
    boms:
      n2o-platform-bom:
        groupId: net.n2oapp.platform
        artifactId: n2o-boot-dependencies
        version: ${project.version}
        repositories: i-novus-releases