Этот проект обеспечивает быстрый способ подключения интернационализации к проекту.

= Возможности

* Удобный класс `Messages` для локализации сообщений по коду и аргументам
* Автоматическая регистрация `MessageSource`, `MessageSourceAccessor`
* Сканирование любых файлов локализации в определенном пакете
(настройка `i18n.global.package-name`, по умолчанию в `messages`)
* Класс исключения `UserException` с поддержкой локализации сообщений

= Подключение

Для автоматического подключения интернационализации нужно добавить зависимость:
[source,xml]
----
<dependency>
  <groupId>net.n2oapp.platform</groupId>
  <artifactId>n2o-platform-i18n</artifactId>
</dependency>
----

= Использование

=== Локализация

Чтобы локализовать сообщение, достаточно подключить `Messages` в Spring классе:
[source,java]
----
@Autowired
private Messages messages;
...
messages.getMessage("example.code", "первый параметр", "второй");
----


=== Локализованные исключения

Для выбрасывания исключений с кодом сообщения и параметрами используется класс `UserException`:
[source,java]
----
throw new UserException("example.code").set("раз").set("два");
----

=== Хранение сообщений

[WARN]
====
Базовое имя файла локализации должно быть уникально!
====

Коды сообщений должны храниться в файлах с базовым именем `messages.properties`, расположенных в корне ресурсов проекта.
По умолчанию используется системная локаль. Пример файла с английской локалью: `messages_en.properties`.

[source,text]
----
example.code=Пример сообщения с параметрами {0} и {1}
----