= Документация
:toc:
:toclevels: 3
:toc-title: Содержание

= Описание
Стартер предназначен для jwt аутентификации запросов от клиентов к микросервисам,
а так же для проксирования токенов от микросервиса к микросервису.

= Возможности

* Автоматическое подключение stateless аутентификации по jwt к микросервису
* Получение пользователя обычным для spring security способом (SecurityContextHolder и т.п.)
* Прозрачная отправка jwt через RestTemplate
* Прозрачная отправлка jwt через feign client при подключении n2o-platform-starter-feign-client
* Прозрачная отправка jwt по REST при подключении n2o-platform-starter-web

= Подключение

Добавьте зависимость:

[source,xml]
----
<dependency>
  <groupId>net.n2oapp.platform</groupId>
  <artifactId>n2o-platform-starter-jwt</artifactId>
</dependency>
----

Добавьте аннотацию `@EnableResourceServer` в конфигурацию микросервиса.

Задайте адрес получения сертификата сервера аутентификации через настройку `n2o.platform.security.key-set-uri`:
```
n2o.platform.security.key-set-uri=http://localhost:8888/auth/realms/test/protocol/openid-connect/certs
```
Микросервис скачает сертификаты и будет валидировать токены на соответствие.

В процессе валидации токена требуется, чтобы в jwt было задано значение поля `aud` соответствующее идентификатору ресурса микросервиса.
Идентификатор ресурса задается настройкой `n2o.platform.security.resource-id`:
```
n2o.platform.security.resource-id=test
```
Он совпадает с идентификатором клиента (`client-id`) который может получать доступ к этому ресурсу.

Для отключения валидации поля `aud` можно задать настройку:

```
n2o.platform.security.check-aud=false
```

По умолчанию включено (true).

Если необходимо выключить проверку действительности токена задайте настройку `n2o.platform.security.check-token-expired`:
```
n2o.platform.security.check-token-expired=false
```
По умолчанию включено (true).

Клиент может получить новый токен, если текущий токен недействителен или отсутствует.
Для этого необходимо задать следующие настройки:
```
#Адрес сервера аутентификации
n2o.platform.security.access-token-uri=http://localhost:8888/auth/realms/test/protocol/openid-connect/token
#Идентификатор клиента
n2o.platform.security.client-id=test
#Секретный код клиента
n2o.platform.security.client-secret=qwerty
```

Если микросервис выпполняет запросы к другим авторизованным микросервисам с тем же идентификатором ресурса,
то задавать настройку `n2o.platform.security.resource-id` не требуется, достаточно задать `n2o.platform.security.client-id`.

= Использование

Чтобы отправить запрос с аутентификацией через `RestTemplate` используйте бин `OAuth2RestOperations`:

[source,java]
----
@Autowired
private OAuth2RestOperations restOperations;
...
restOperations.getForObject(url, MyEntity.class);//Запросы с проксированием текущего токена
----

Чтобы получить имя пользователя можно использовать объект `OAuth2Authentication` в аргументах контроллера:

[source,java]
----
@GetMapping("/greeting")
public String greeting(OAuth2Authentication authentication) {
    return "Hello " + authentication.getPrincipal();
}
----

Или использовать статический метод `SecurityContextHolder.getContext`:

[source,java]
----
((OAuth2Authentication)SecurityContextHolder.getContext().getAuthentication()).getPrincipal()
----

Для авторизации сервисов по паттерну запроса нужно создать конфигурацию расширяя класс `N2oPlatformResourceServerConfigurerAdapter`:

[source,java]
----
@Configuration
@EnableResourceServer
public class SecurityConfig extends N2oPlatformResourceServerConfigurerAdapter {
    @Override
    public void configure(ExpressionUrlAuthorizationConfigurer<HttpSecurity>.ExpressionInterceptUrlRegistry requests) throws Exception {
        requests.mvcMatchers("/greeting").hasRole("ROLE_USER")
            .anyRequest().authenticated();
    }
}

----
