= Документация
:toc:
:toclevels: 3
:toc-title: Содержание

= Описание
Стартер предназначен для jwt аутентификации запросов от клиентов к микросервисам,
а так же для проксирования токенов от микросервиса к микросервису.

= Возможности

* Автоматическое подключение stateless аутентификации по jwt к микросервису
* Получение пользователя обычным для spring security способом (SecurityContextHolder и т.п.)
* Прозрачная отправка jwt через RestTemplate
* Прозрачная отправлка jwt через feign client при подключении n2o-platform-starter-feign-client
* Прозрачная отправка jwt по REST при подключении n2o-platform-starter-web

= Подключение

Добавьте зависимость:

[source,xml]
----
<dependency>
  <groupId>net.n2oapp.platform</groupId>
  <artifactId>n2o-platform-starter-jwt</artifactId>
</dependency>
----

Добавьте аннотацию `@EnableResourceServer` в конфигурацию микросервиса.

= Использование

Чтобы отправить запрос с аутентификацией через `RestTemplate` используйте бин `OAuth2RestOperations`:

[source,java]
----
@Autowired
private OAuth2RestOperations restOperations;
...
restOperations.getForObject(url, MyEntity.class);//Запросы с проксированием текущего токена
----

Чтобы получить имя пользователя можно использовать объект `OAuth2Authentication` в аргументах контроллера:

[source,java]
----
@GetMapping("/greeting")
public String greeting(OAuth2Authentication authentication) {
    return "Hello " + authentication.getPrincipal();
}
----

Или использовать статический метод `SecurityContextHolder.getContext`:

[source,java]
----
((OAuth2Authentication)SecurityContextHolder.getContext().getAuthentication()).getPrincipal()
----

Для авторизации сервисов по паттерну запроса нужно создать конфигурацию расширяя класс `N2oPlatformResourceServerConfigurerAdapter`:

[source,java]
----
@Configuration
@EnableResourceServer
public class SecurityConfig extends N2oPlatformResourceServerConfigurerAdapter {
    @Override
    public void configure(ExpressionUrlAuthorizationConfigurer<HttpSecurity>.ExpressionInterceptUrlRegistry requests) throws Exception {
        requests.mvcMatchers("/greeting").hasRole("ROLE_USER")
            .anyRequest().authenticated();
    }
}

----
