:toc:
:toclevels: 3
:toc-title: Содержание

== Возможности

* Передача информации о пользователе от сервиса к сервису.

== Подключение

Добавьте зависимость:

[source,xml]
----
<dependency>
  <groupId>net.n2oapp.platform</groupId>
  <artifactId>n2o-platform-userinfo-starter</artifactId>
</dependency>
----

Для автоматической работы при использовании <rest> провайдера данных в n2o xml, нужно так же добавить зависимость

[source,xml]
----
<dependency>
  <groupId>net.n2oapp.platform</groupId>
  <artifactId>n2o-platform-starter-web</artifactId>
  <version>${n2o.version}</version>
</dependency>
----

== Использование

=== Ограничения

Функционал данного модуля работает только при использовании преднастроенных  <<user-content-клиенты,клиентов>> или при интеграции <<user-content-интерцепторы,интерцепторов>> в свой клиент.

=== Настройки

[source,properties]
----
#Имя заголовка в котором передаются данные о пользователе.
#Нужно указывать и в сервисе отправляющем и принимающем данные.
#По умолчанию n2o-user-info
n2o.platform.userinfo.header-name=n2o-user-info

#Отправлять ли данные по умолчанию(без аннотации). По умолчанию отправлять.
n2o.platform.userinfo.send-by-default=true

#Отправка только username пользователя. По умолчанию false.
n2o.platform.userinfo.username-only=false

----

=== @UserInfo

Аннотация для указания нужно ли передавать информацию о пользователе из данного метода\класса.

Аннотация метода переопределяет аннотацию класса.
Считывание аннотации происходит только при вызове метода через прокси.
В примере ниже при вызове метода method2 из method1, данные отправлены НЕ будут.
При вызове method2 из "вне"(обращение к методу бина) данные будут отправлены.

[source,java]
----
@Service/@Component/@Bean
@UserInfo(false)
public class SomeService {
    @Autowired
    @Qualifier("platformWebClient")
    WebClient webClient;

    @UserInfo(value = false)
    public void method1() {
        webClient.get().retrieve().bodyToMono(String.class).block();
        method2();
    }

    @UserInfo(value = true)
    public void method2() {
        webClient.get().retrieve().bodyToMono(String.class).block();
    }
}
----

[[user-content-клиенты]]
=== Клиенты

Клиенты с интегрированными интерцепторами, отправляющие информацию о пользователе.

* WebClient(spring)

[source,java]
----
@Autowired
@Qualifier("platformWebClient")
WebClient webClient;
----

* RestTemplate

[source,java]
----
@Autowired
@Qualifier("platformRestTemplate")
RestTemplate restTemplate;
----

[[user-content-интерцепторы]]
=== Интерцепторы

Добавляют в запрос заголовок с информацией о пользователе.

Модуль предоставляет интерцепторы для:

* WebClient(spring)

[source,java]
----
@Autowired
@Qualifier("userinfoExchangeFilterFunction")
ExchangeFilterFunction userinfoExchangeFilterFunction;
----

* RestTemplate

[source,java]
----
@Autowired
@Qualifier("userinfoRestTemplateInterceptor")
ClientHttpRequestInterceptor userinfoRestTemplateInterceptor;
----

* Feign

[source,java]
----
@Autowired
@Qualifier("userinfoFeignInterceptor")
RequestInterceptor userinfoFeignInterceptor;
----

=== Расширение

"Из коробки" модуль предназначен для работы совместно с security-admin и в качестве principals(`org.springframework.security.core.Authentication.getPrincipal`) ожидает модель `net.n2oapp.security.auth.common.OauthUser`.

При использовании другой модели необходимо создать бин расширяющий `net.n2oapp.platform.userinfo.mapper.PrincipalToJsonAbstractMapper`.
В качестве параметра указать ожидаемый тип principals.

Смапить данные в модель `net.n2oapp.platform.userinfo.UserInfoModel`, преобразовать в json.

[source,java]
----
@Bean
public PrincipalToJsonAbstractMapper customPrincipalToJsonMapper(){
    return new PrincipalToJsonAbstractMapper<CustomPrincipal>() {
        @Override
        public String map(CustomPrincipal principal) {
            UserInfoModel userInfo = new UserInfoModel(principal.getUsername());

            userInfo.email = principal.getCustomEmailField();
            //можно использовать любой сбособ получения Json строки
            return new Gson().toJson(userInfo);
        }
    };
}
----



В случае необходимости расширить модель UserInfoModel, нужно будет также переопределить `net.n2oapp.platform.userinfo.mapper.JsonToPrincipalAbstractMapper` и создать бин.

[source,java]
----
public class CustomUserInfoModel extends UserInfoModel{
        public String someCustomField;
    }
----

[source,java]
----
@Bean
public JsonToPrincipalAbstractMapper customJsonToPrincipalMapper(){
    return new JsonToPrincipalAbstractMapper<CustomUserInfoModel>(){
        @Override
        public CustomUserInfoModel map(String principal) {
            //можно использовать любой сбособ парсинга Json
            CustomUserInfoModel userInfo = new Gson().fromJson(principal, new TypeToken<CustomUserInfoModel>() {
            }.getType());
            //Если используются org.springframework.security.core.GrantedAuthority из security-admin
            //Иначе зависит от вашей реализации
            userInfo.authorities = collectAuthority(userInfo);
            return userInfo;
        }
    };
}
----

При возникновении проблем с сериализацией расширенной `UserInfoModel` нужно создать бин `net.n2oapp.platform.userinfo.mapper.UserInfoToJsonMapper` и передать ему сконфигурированный экземляр Gson

[source,java]
----
@Bean
public PrincipalToJsonAbstractMapper userInfoToJsonMapper() {
    GsonBuilder gsonBuilder = new GsonBuilder();
    .....
    return new UserInfoToJsonMapper(gsonBuilder.create());
}
----

Либо полностью переопределить `UserInfoToJsonMapper` или его родителя и создать бин.

[source,java]
----
@Bean
public PrincipalToJsonAbstractMapper userInfoToJsonMapper() {
    return new UserInfoToJsonMapper<CustomUserInfoModel>(){
        @Override
        public String map(CustomUserInfoModel principal) {
            String json;
            ...
            сериализация
            ...
            return json;
        }
    };
}
----