:toc:
:toclevels: 3
:toc-title: Содержание

== Возможности

* Передача информации о пользователе от сервиса к сервису.

== Подключение

Добавьте зависимость:

[source,xml]
----
<dependency>
  <groupId>net.n2oapp.platform</groupId>
  <artifactId>n2o-platform-userinfo-starter</artifactId>
</dependency>
----

Для автоматической работы при использовании <rest> провайдера данных в n2o xml, нужно так же добавить зависимость

[source,xml]
----
<dependency>
  <groupId>net.n2oapp.platform</groupId>
  <artifactId>n2o-platform-starter-web</artifactId>
  <version>${n2o.version}</version>
</dependency>
----

== Использование

=== Ограничения

Функционал данного модуля работает только при использовании преднастроенных  <<clients,клиентов>> или при интеграции <<interceptors,интерцепторов>> в свой клиент.

=== Настройки

[source,properties]
----
#Имя заголовка в котором передаются данные о пользователе.
#Нужно указывать и в сервисе отправляющем и принимающем данные.
#По умолчанию n2o-user-info
n2o.platform.userinfo.header-name=n2o-user-info

#Отправлять ли данные по умолчанию(без аннотации). По умолчанию отправлять.
n2o.platform.userinfo.send-by-default=true

#Отправка только username пользователя. По умолчанию false.
n2o.platform.userinfo.username-only=false

----

=== @UserInfo

Аннотация для указания нужно ли передавать информацию о пользователе из данного метода\класса.

Аннотация метода переопределяет аннотацию класса.
Считывание аннотации происходит только при вызове метода через прокси.
В примере ниже при вызове метода method2 из method1, данные отправлены НЕ будут.
При вызове method2 из "вне"(обращение к методу бина) данные будут отправлены.

[source,java]
----
@Service/@Component/@Bean
@UserInfo(false)
public class SomeService {
    @Autowired
    @Qualifier("userInfoWebClient")
    WebClient webClient;

    @UserInfo(value = false)
    public void method1() {
        webClient.get().retrieve().bodyToMono(String.class).block();
        method2();
    }

    @UserInfo(value = true)
    public void method2() {
        webClient.get().retrieve().bodyToMono(String.class).block();
    }
}
----

[#clients]
=== Клиенты

Клиенты с интегрированными интерцепторами, отправляющие информацию о пользователе.

* WebClient(spring)

[source,java]
----
@Autowired
@Qualifier("userInfoWebClient")
WebClient webClient;
----

* RestTemplate

[source,java]
----
@Autowired
@Qualifier("userInfoRestTemplate")
RestTemplate restTemplate;
----

[#interceptors]
=== Интерцепторы

Добавляют в запрос заголовок с информацией о пользователе.

Модуль предоставляет интерцепторы для:

* WebClient(spring)

[source,java]
----
@Autowired
@Qualifier("userinfoExchangeFilterFunction")
ExchangeFilterFunction userinfoExchangeFilterFunction;
----

* RestTemplate

[source,java]
----
@Autowired
@Qualifier("userinfoRestTemplateInterceptor")
ClientHttpRequestInterceptor userinfoRestTemplateInterceptor;
----

* Feign

[source,java]
----
@Autowired
@Qualifier("userinfoFeignInterceptor")
RequestInterceptor userinfoFeignInterceptor;
----

=== Расширение

Из коробки модуль предназначен для работы совместно с security-admin и в качестве principals(org.springframework.security.core.Authentication.getPrincipal) ожидает модель net.n2oapp.security.auth.common.OauthUser.

При использование другой модели необходимо создать бин расширяющий net.n2oapp.platform.userinfo.mapper.PrincipalToJsonAbstractMapper.
В качестве параметра указать ожидаемый тип principals.
Смапить данные в модель net.n2oapp.platform.userinfo.UserInfoModel, преобразовать в json.

В случае необходимости расширить модель UserInfoModel, нужно будет также переопределить net.n2oapp.platform.userinfo.mapper.JsonToPrincipalAbstractMapper и net.n2oapp.platform.userinfo.mapper.UserInfoToJsonMapper и создать их бины.