# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Stage release to Maven Central

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v3  # running setup-java again overwrites the settings.xml
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: SONATYPE_USER # env variable for username in deploy
          server-password: SONATYPE_PASSWORD # env variable for token in deploy

      - name: Publish to Apache Maven Central
        run: mvn deploy -Pn2o-platform-release -DskipTests=true
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
